[package]
name = "examples"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "pipe_basic_usage"
path = "pipe_basic_usage.rs"

[[bin]]
name = "tokio_producer"
path = "tokio_producer.rs"

[[bin]]
name = "tokio_consumer"
path = "tokio_consumer.rs"

[dependencies]
mi7.workspace = true
tokio.workspace = true
serde.workspace = true
bincode = "1.3"
serde_json = "1.0"
libc = "0.2"
